steps:
  - label: checks
    command: |
      pnpm i  
      pnpm check

  - label: build check
    command: |
      ci-docker-login
      IMAGE_TAG="$BUILDKITE_BUILD_ID" ./scripts/ci/docker-build.sh

  # - label: e2e test
  #   command: scripts/ci/e2e-tests
  #   artifact_paths:
  #     - '.playwright/**/*'

  - wait

  - label: Build & deploy
    branches: $BUILDKITE_PIPELINE_DEFAULT_BRANCH
    command: |
      ci-docker-login
      # IMAGE_TAG=production \
      #   ./scripts/ci/docker-build.sh push
      # deploy-eamon-sh-container example
      # flush-eamon-sh-varnish-cache example.eamon.sh
    env:
      IMAGE_TAG: production
