steps:
  - label: checks
    command: |
      pnpm i  
      pnpm check

  - label: build check
    command: |
      ci-docker-login
      IMAGE_TAG="$BUILDKITE_BUILD_ID" ./scripts/ci/docker-build.sh

  - label: e2e test
    command: scripts/ci/e2e-tests
    artifact_paths:
      - '.playwright/**/*'

  - wait

  - label: Build & deploy
    branches: $BUILDKITE_PIPELINE_DEFAULT_BRANCH
    command: |
      ci-docker-login
      IMAGE_TAG=production \
        ./scripts/ci/docker-build.sh push
      update-media-server-container example-app
      flush-eamon-sh-varnish-cache example-app.eamon.sh
    env:
      IMAGE_TAG: production

  - wait

  - label: Smoke Test
    command: scripts/ci/e2e-tests
    env:
      PLAYWRIGHT_BASE_URL: https://example-app.eamon.sh
    artifact_paths:
      - '.playwright/**/*'
