
/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(platform(Dependencies.wireBom))
    implementation(Dependencies.wireSchema)
    implementation(Dependencies.kotlinxSerializationJson)
}

application {
    // Define the main class for the application.
    mainClass.set("example.app.AppKt")
}
